apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: guardrails-detector-runtime-hap
  annotations:
    openshift.io/display-name: guardrails-detector-runtime-hap
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-name: guardrails-detector-huggingface-runtime
  labels:
    opendatahub.io/dashboard: 'true'

spec:
  annotations:
    prometheus.io/port: '8080'
    prometheus.io/path: '/metrics'
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: guardrails-detector-hf-runtime
  containers:
    - name: kserve-container
      image: registry.redhat.io/rhoai/odh-guardrails-detector-huggingface-runtime-rhel9:v3.0
      command:
        - uvicorn
        - app:app
      args:
        - "--workers"
        - "4"
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "8000"
        - "--log-config"
        - "/common/log_conf.yaml"
      env:
        - name: MODEL_DIR
          value: /mnt/models
        - name: HF_HOME
          value: /tmp/hf_home
      ports:
        - containerPort: 8000
          protocol: TCP

---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: hap-detector
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: hap-detector
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    serving.kserve.io/deploymentMode: RawDeployment

spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: guardrails-detector-hf-runtime
      name: ''
      runtime: guardrails-detector-runtime-hap
      storageUri: 'oci://quay.io/trustyai_testing/detectors/granite-guardian-hap-38m:v1.0'
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
        nvidia.com/gpu: '0'
      requests:
        cpu: '1'
        memory: 2Gi
        nvidia.com/gpu: '0'

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hap-detector-route
spec:
  to:
    kind: Service
    name: hap-detector-predictor
