apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails
spec:
  orchestratorConfig: "guardrails-config"
  replicas: 1
  enableBuiltInDetectors: True  
  enableGuardrailsGateway: True  
  guardrailsGatewayConfig: "guardrails-gateway" 
  otelExporter:
    otlpProtocol: "grpc"
    otlpMetricsEndpoint: "eclipse.home.glroland.com:4317"
    otlpTracesEndpoint: "eclipse.home.glroland.com:4317"
    enableMetrics: true    
    enableTracing: true
